# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(LiblineaR)
    library(parsnip)
    library(recipes)
    library(workflows)
}
b <- board_folder(path = "/var/folders/ym/x_d48cqd3xg4c26y8chndm5w0000gn/T/RtmpfcwEr7/pins-115844da83f9c")
v <- vetiver_pin_read(b, "biv_svm", version = "20220627T144500Z-fe61c")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
