sectors_lse_etf_ <- structure(list(SYMBOL = c("XLCP", "XLYP", "XLPP", "XLEP", "XLFQ", 
  "XLVP", "XLIP", "XLBP", "XREP", "XLKQ", "XLUP", "ESIC", "ESIS", 
  "ESIE", "ESIF", "ESIH", "ESIN", "ESIT", "ICDU", "ICSU", "IESU", 
  "UIFS", "IHCU", "IISU", "IITU", "IMSU", "IUSU", "5HEP", "GXLC"
), `FUND DESCRIPTION (CLICK LINK FOR MORE DETAILS)` = c("Invesco Communications S&P US Select Sector UCITS ETF", 
  "Invesco Consumer Discretionary S&P US Select Sector UCITS ETF", 
  "Invesco Consumer Staples S&P US Select Sector UCITS ETF", "Invesco Energy S&P US Select Sector UCITS ETF", 
  "Invesco Financials S&P US Select Sector UCITS ETF", "Invesco Health Care S&P US Select Sector UCITS ETF", 
  "Invesco Industrials S&P US Select Sector UCITS ETF", "Invesco Materials S&P US Select Sector UCITS ETF", 
  "Invesco Real Estate S&P US Select Sector UCITS ETF", "Invesco Technology S&P US Select Sector UCITS ETF", 
  "Invesco Utilities S&P US Select Sector UCITS ETF", "iShares Msci Europe Consumer Discretionary Sector UCITS ETF", 
  "iShares MSCI Europe Consumer Staples Sector UCITS ETF", "iShares MSCI Europe Energy Sector UCITS ETF", 
  "iShares MSCI Europe Financials Sector UCITS ETF", "iShares MSCI Europe Health Care Sector UCITS ETF", 
  "iShares MSCI Europe Industrials Sector UCITS ETF", "iShares MSCI Europe Information Technology Sector UCITS ETF", 
  "iShares S&P 500 Consumer Discretionary Sector UCITS ETF", "iShares S&P 500 Consumer Staples Sector UCITS ETF", 
  "iShares S&P 500 Energy Sector UCITS ETF", "iShares S&P 500 Financials Sector UCITS ETF USD ACC", 
  "iShares S&P 500 Health Care Sector UCITS ETF", "iShares S&P 500 Industrials Sector UCITS ETF", 
  "iShares S&P 500 Information Technology Sector UCITS ETF", "iShares S&P 500 Materials Sector UCITS ETF", 
  "iShares S&P 500 Utilities Sector UCITS ETF", "Ossiam ESG Low Carbon Shiller Barclays Cape US Sector UCITS ETF", 
  "SPDR S&P U.S. Communication Services Select Sector UCITS ETF"
), SYMBOL_2 = c("XLCP", "XLYP", "XLPP", "XLEP", "XLFQ", "XLVP", 
  "XLIP", "XLBP", "XREP", "XLKQ", "XLUP", "ESIC", "ESIS", "ESIE", 
  "ESIF", "ESIH", "ESIN", "ESIT", "ICDU", "ICSU", "IESU", "UIFS", 
  "IHCU", "IISU", "IITU", "IMSU", "IUSU", "5HEP", "GXLC"), CURRENCY = c("GBP", 
    "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", 
    "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", 
    "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", "GBP", 
    "GBP")), row.names = c(NA, -29L), spec = structure(list(cols = list(
      SYMBOL = structure(list(), class = c("collector_character", 
        "collector")), `FUND DESCRIPTION (CLICK LINK FOR MORE DETAILS)` = structure(list(), class = c("collector_character", 
          "collector")), SYMBOL_2 = structure(list(), class = c("collector_character", 
            "collector")), CURRENCY = structure(list(), class = c("collector_character", 
              "collector"))), default = structure(list(), class = c("collector_guess", 
                "collector")), delim = "\t"), class = "col_spec"),  class = c("spec_tbl_df", 
                  "tbl_df", "tbl", "data.frame"))